# Utilise une image de base très légère (Alpine)
FROM alpine:latest

# Mise à jour et installation du serveur web Nginx
RUN apk update && \
    apk add nginx && \
    rm -rf /var/cache/apk/*

# Création d'une page HTML simple comme preuve de déploiement
RUN mkdir -p /var/www/localhost/htdocs && \
    echo "<h1>Application Deployed via Terraform laC!</h1>" > /var/www/localhost/htdocs/index.html

RUN echo 'server { listen 80; root /var/www/localhost/htdocs; index index.html; }' > /etc/nginx/http.d/default.conf


# Expose le port par défaut de Nginx
EXPOSE 80

# Commande pour démarrer Nginx en mode non-démonisé
CMD ["nginx", "-g", "daemon off;"]